language: bash
services: docker
env:
  matrix:
  - VERSION=PHP_5_6
  - VERSION=PHP_7_0
  - VERSION=PHP_7_1
  - VERSION=PHP_7_2
  - VERSION=PHP_7_3
  - VERSION=PHP_HEAD
  global:
  - secure: oAueCGBDgQZVpj8ds3i2SGef3isbbh/LSwmciiMfPeEG1QNQu3kpvHvPXtMmuy6ZZbZiMJ6vEhnTd79xsVa4UBHiCzOsJMAF7J/OZy3JDEDgUMVc6cPchp9xL4rPZuDy7frTYqUIdyklHvoWwiGDqDTKSj+DAXIjh1TVj+lO+PJQcBwk7N1zPlOJBeQ3zCNFaTOKjtbnZQAlKqVLMbkqE9uAZ4kIECIje16P1YJ5pYiuU3No7uQtEFMCPPqc6l7JLLFV0PelEotsz2Jvl76UqFo9ErZgquy6OPlRWpilAOeaZgcrnnH2wfYVcAamgNwQfwAjTnaTexiibyxny491duS/nH1vAd29l75d9EnSblyECmCtTlEIRQOw8xO42GVnpGelYdH7JODNptW70yq5ALFzitf5EPx4po5h6FN2nV+cOuwf5lHCMRKNQKG4mZMBXeJMDmIQ5n2M1HI6sY8nnbFJbeC8TVr1/Pf/uc1eXfUip0xP/WrybhbsQnMb1xfLhX0O7E7n4xXAWvdT4Ce2+Y2V/qh9Jacl9cQKKD+26r5Sgxlm1ZVhFFdAzi7m0yf/2RbwPOfbb6I8tOWgGG39Ejq7dq/iGHdrjSOBcjMWzEUzLrmWa1HkljJ4Fo0Cw+puJ+SDSmFoenIWSmrvL6xr8stfJwQTlwwS/3dsN7ZEo3w=
  - secure: FkWrbgaCrGzFZX0KJxdaNTeHzKiQNq2/fCRQXb+6VtpvPqJorlQCSdQWvT2fzr+yuMRvXzkEaChlpudtyM6yz0/7stpFr2X2ES4L/E+peaZTsmzXYU4AjQO+RfdDTeBjrnkiQZS2TRj9BNrzu2u2wCfudZ3grcby8pQNYZA6yEJWhPt+1so8dUDpH/GRpvwX2f5Joe0mIyCfFZrt4nKYfIQg9vb3s8Ykb29qQN1FWi7yQ2QRUyGwwTdaYa23ioIc7gMRVrIyEiz0rD7sZTQF1s+iNe7YIbG8yI957QubJ97u0QlwCrf6NjF+G91uqKMp94klZZoaQrUmx783yb6x7rXfcddt1Ku9D5AyFab+Fsa10JxuHw/uQ9oD3fdbLa1dSlyNpxr1f/Z/i5VvPt1vzMMpDHWBKA4hOgIBeEpTbhyaAmdyiYEka92hyPsmM33BGl3IQrIf8dFUWN5u/KRP0iXgmOpntQM4f0eBlwNo2LZg3x8nxP5WNnPLOai8SRr2dxX5gM9SALsXnWPM2LWY24jzN+j+3zD2KoP7BcZ9segs6IxLHvO9hftw+kovyLOErHFCVk3ejtdKXVqHnmvJtxMyqldSQTKgLjmCAWufNgWdc/x4KatGc2RioEPCuGv1y4wWGgscdLzVureI8BwD3wcT9Uz+yULdlGFir1WVvlw=
  - secure: Ma5TzXLF8Drp7O4JMagaUZ+EDBznODO1Y33+OlsFOPEbd8gvO4PJnLOaglojNVLwPcORiaMJ2Tk+chOlfi2AtV+j6desh5MlCjJjFZXsBdIAsA+rpZuJz5YukxDRyFe6EetLFDrrlbYJb9SdDH4PQSta5rGXShMz13KCqwjNBTzkAE+asLr+1DlcQXDVtMHCLkn6ojMXttNdvLevd1p2vH+CjGHczmDhwB0WQEmw/YWnPSB4wqxiiXZgZcSef3jm46Nble+6Q3Xtxfmw5W42uqYv+13OP0lgPeAivtYvzKo8xK/HKOhXdVcEr9W9HxZOPF11dyEkq+XzKxmLTFifvngeK+mmBeGzsKKMTWBaNXcjXUktq2guE+u0ZRQuxfgF5y3ogQfIGCYV05AAQEq2SAnTOkqR5Jtf6ZpqsQCte0WBx5XSQ/sDL3hpLdBOkrg8x7yUu+Xn6qrqR7+I6pI/HxW2nVwlQ46nuvvBydtLaHvjG8dK5akq/eiwD9M1ROLKKHDpCUEuRLrO4Auf3Hz5eDUeyGNaYtKFDTOdx5FWlI0IzXB7/2qo1QuA+C0jKuKSKqTkQXAEHhcVGWvuNOqULoXRfuqcGuql/0rqFwW2GO1cUFddMAxctbfuoatgVNwH5j5CMmV9o6Ux/bsozvtjVOqHJ51j/QsMhKHbDQ3M8jI=
before_script:
- env | sort
- cd "$VERSION"
- image="phptestfestbrasil/phptt:${VERSION}"
script:
- travis_retry docker build -t "$image" .
after_script:
- docker images
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- docker push "$image"
