#!/bin/sh
set -e

dir=/usr/src/php

usage() {
	echo "usage: $0 COMMAND"
	echo
	echo "Manage php source zip archive lifecycle."
	echo
	echo "Commands:"
	echo "   extract  extract php source zip archive into directory $dir if not already done."
	echo "   delete   delete extracted php source located into $dir if not already done."
	echo
}

case "$1" in
	extract)
		mkdir -p "$dir"
		if [ -f "/usr/src/php-src-PHP-7.4.zip" ]; then
			unzip -qq /usr/src/php-src-PHP-7.4.zip -d "/tmp" && mv /tmp/php-src-PHP-7.4/* "$dir"
		fi
		;;

	delete)
		rm -rf "$dir"
		;;

	*)
		usage
		exit 1
		;;
esac
